/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import Consultas.CONSULTASDAO;
import ConexionDB.Conexion_DB;
import Configuraciones.Configuraciones;
import DBObjetos.*;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author braul
 */
public class FormularioNuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FormularioNuevoUsuario
     */
    private String rolSeleccionado;
    private ArrayList<String> respuestasDadas = new ArrayList<>();
    

    public FormularioNuevoUsuario(String rol) {
       this.rolSeleccionado = rol; // Establece el rol para el formulario
        initComponents();
        lblRoles.setText(rolSeleccionado); // Muestra el rol en la etiqueta
        
       
      // Y para txtRespuesta así:
        

        AbrirVentana();
        
        Estilos.addPlaceholderStyle(Nombre);
        Estilos.addPlaceholderStyle(Apellido);
        Estilos.addPlaceholderStyle(Correo);
        Estilos.addPlaceholderStyle(nomUsuario);
        Estilos.addPlaceholderStyle(Contraseña);
    }

private void AbrirVentana() {

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);  // Evita que la ventana se cierre automáticamente
    addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrarYVolverAConfiguraciones();
        }
    });
}
    
    private Configuraciones configuraciones;

public void setConfiguraciones(Configuraciones config) {
    this.configuraciones = config;
}

private void cerrarYVolverAConfiguraciones() {
    if (configuraciones != null) {
        configuraciones.mostrar();  // Este método hace la ventana Configuraciones visible
    }
    this.dispose();  // Cierra FormularioNuevoUsuario
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmensaje = new javax.swing.JLabel();
        nomUsuario = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        lblRoles = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomUsuario.setText("Nombre de usuario");
        nomUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomUsuarioFocusLost(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre");
        Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreFocusLost(evt);
            }
        });

        Apellido.setText("Apellido");
        Apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ApellidoFocusLost(evt);
            }
        });

        Correo.setText("Correo");
        Correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CorreoFocusLost(evt);
            }
        });

        lblRoles.setText("REGISTRARSE");

        Contraseña.setText("Contraseña");
        Contraseña.setEchoChar('\u0000');
        Contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContraseñaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar)
                            .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lblRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRoles)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(nomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnAgregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     // Obtener valores de los campos de texto
    String usuario = nomUsuario.getText().trim();
    String contraseñaPlana = Contraseña.getText().trim();
    String correo = Correo.getText().trim();
    String nombre = Nombre.getText().trim();
    String apellido = Apellido.getText().trim();

    // Verifica que se hayan ingresado todos los campos
    boolean camposValidos = !usuario.isEmpty() && !contraseñaPlana.isEmpty() && 
                            !correo.isEmpty() && !nombre.isEmpty() && !apellido.isEmpty();

    // Configura el color de las etiquetas según la validez de los campos
//    lblUsuario.setForeground(!usuario.isEmpty() ? Color.BLACK : Color.RED);
//    lblContraseña.setForeground(!contraseñaPlana.isEmpty() ? Color.BLACK : Color.RED);
//    lblCorreo.setForeground(!correo.isEmpty() ? Color.BLACK : Color.RED);
//    lblNombre.setForeground(!nombre.isEmpty() ? Color.BLACK : Color.RED);
//    lblApellido.setForeground(!apellido.isEmpty() ? Color.BLACK : Color.RED);
    
    // Validación del formato del correo electrónico
    boolean esCorreoValido = correo.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$");
//    lblCorreo.setForeground(esCorreoValido ? Color.BLACK : Color.RED);

    if (!esCorreoValido) {
        JOptionPane.showMessageDialog(this, "El formato del correo electrónico no es válido.");
        return;
    }
    // Verifica que se hayan respondido 3 preguntas
    if (camposValidos) {
        try {
            // Hashea la contraseña antes de enviarla a la base de datos
            String contraseñaHasheada = HashingUtil.hashPassword(contraseñaPlana);
            if (contraseñaHasheada == null) {
                throw new IllegalArgumentException("No se pudo hashear la contraseña.");
            }
            
            // Aquí se debería crear una instancia de CONSULTASDAO (idealmente debería ser UsuarioDAO)
            CONSULTASDAO dao = new CONSULTASDAO(Conexion_DB.getConexion());
            
            // El método crearEmpleado ahora también incluye correo, nombre y apellido
            Usuario.Rol rolEnum = Usuario.Rol.valueOf(rolSeleccionado.toUpperCase());
            boolean exito = dao.crearEmpleadosinToken(usuario, contraseñaHasheada, rolEnum, correo, nombre, apellido);
            //boolean exi = dao.crearEmpleado(usuario, contraseñaHasheada, rolEnum, contraseñaPlana, correo, nombre, apellido);

          
            
            
            if (exito) {
                JOptionPane.showMessageDialog(this, "Empleado agregado correctamente.");
                // Restablece el formulario
                resetFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "El nombre de usario ya existe, cree uno nuevo.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + ex.getMessage());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    } else {
        // Mensajes específicos para cada tipo de error de validación
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos requeridos.");
        
    }
    AbrirVentana();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusGained
        if(Nombre.getText().equals("Nombre")){
            Nombre.setText(null);
            Nombre.requestFocus();
            Estilos.removePlaceholderStyle(Nombre);
        }
    }//GEN-LAST:event_NombreFocusGained

    private void NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusLost
        if(Nombre.getText().length()==0){
            Estilos.addPlaceholderStyle(Nombre);
            Nombre.setText("Nombre");
        }
    }//GEN-LAST:event_NombreFocusLost

    private void ApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidoFocusGained
        if(Apellido.getText().equals("Apellido")){
            Apellido.setText(null);
            Apellido.requestFocus();
            Estilos.removePlaceholderStyle(Apellido);            
        }
    }//GEN-LAST:event_ApellidoFocusGained

    private void ApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidoFocusLost
        if(Apellido.getText().length()==0){
            Estilos.addPlaceholderStyle(Apellido);
            Apellido.setText("Apellido");
        }
    }//GEN-LAST:event_ApellidoFocusLost

    private void CorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CorreoFocusGained
        if(Correo.getText().equals("Correo")){
            Correo.setText(null);
            Correo.requestFocus();
            Estilos.removePlaceholderStyle(Correo);            
        }
    }//GEN-LAST:event_CorreoFocusGained

    private void CorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CorreoFocusLost
        if(Correo.getText().length()==0){
            Estilos.addPlaceholderStyle(Correo);
            Correo.setText("Correo");
        }
    }//GEN-LAST:event_CorreoFocusLost

    private void nomUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomUsuarioFocusGained
        if(nomUsuario.getText().equals("Nombre de usuario")){
            nomUsuario.setText(null);
            nomUsuario.requestFocus();
            Estilos.removePlaceholderStyle(nomUsuario);            
        }
    }//GEN-LAST:event_nomUsuarioFocusGained

    private void nomUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomUsuarioFocusLost
        if(nomUsuario.getText().length()==0){
            Estilos.addPlaceholderStyle(nomUsuario);
            nomUsuario.setText("Nombre de usuario");
        }
        
    }//GEN-LAST:event_nomUsuarioFocusLost

    private void ContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaFocusGained
        if(Contraseña.getText().equals("Contraseña")){
            Contraseña.setText(null);
            Contraseña.requestFocus();
            Contraseña.setEchoChar('*');
            Estilos.removePlaceholderStyle(Contraseña);            
        }
    }//GEN-LAST:event_ContraseñaFocusGained

    private void ContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaFocusLost
        if(Contraseña.getText().length()==0){
            Estilos.addPlaceholderStyle(Contraseña);
            Contraseña.setText("Contraseña");
            //jPasswordField2.setEchoChar('*');
        }
    }//GEN-LAST:event_ContraseñaFocusLost

private void resetFormulario() {
    // Restablecer los campos del formulario
    nomUsuario.setText("");
    Contraseña.setText("");
    Correo.setText("");
    Nombre.setText("");
    Apellido.setText("");    
    lblmensaje.setText("");         // Limpiar mensajes de respuesta
    // Restablecer los colores de las etiquetas a negro
//    lblUsuario.setForeground(Color.BLACK);
//    lblContraseña.setForeground(Color.BLACK);
//    lblCorreo.setForeground(Color.BLACK);
//    lblNombre.setForeground(Color.BLACK);
//    lblApellido.setForeground(Color.BLACK);
}



  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel lblRoles;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField nomUsuario;
    // End of variables declaration//GEN-END:variables
}
