/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INVENTARIO;

import login.Estilos;
import ConexionDB.Conexion_DB;
import DBObjetos.Producto;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Consultas.CONSULTASDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Date;

/**
 *
 * @author Luis
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    
    private int num;
    int numfinal;
    
    
    
    public Add() {
        initComponents();
        
        Estilos.addPlaceholderStyle(Unidades);
        Estilos.addPlaceholderStyle(Caducidad);
        Estilos.addPlaceholderStyle(Contenido);
        Estilos.addPlaceholderStyle(Precio);
        Estilos.addPlaceholderStyle(Marca);
        Estilos.addPlaceholderStyle(Precio);
        Estilos.addPlaceholderStyle(Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Unidades = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        Nombre = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Caducidad = new javax.swing.JTextField();
        cod = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        Contenido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        RETURN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Unidades.setText("Unidades Disponibles");
        Unidades.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UnidadesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UnidadesFocusLost(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UN AREA", "Salchichonería", "Frutas y Verduras", "Panadería", "Galletas y Cereales", "Bebidas", "Productos de Limpieza", "Botanas", "Cuidado Personal", "Congelados" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre");
        Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreFocusLost(evt);
            }
        });

        Precio.setText("Precio");
        Precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PrecioFocusLost(evt);
            }
        });

        Caducidad.setText("Fecha de Caducidad");
        Caducidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CaducidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CaducidadFocusLost(evt);
            }
        });

        cod.setText("CODIGO DE BARRAS");
        cod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Marca.setText("Marca");
        Marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MarcaFocusLost(evt);
            }
        });

        Contenido.setText("Contenido");
        Contenido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContenidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContenidoFocusLost(evt);
            }
        });

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RETURN.setText("REGRESAR");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Caducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RETURN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RETURN)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Caducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)))
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnidadesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UnidadesFocusGained
        if(Unidades.getText().equals("Unidades Disponibles")){
            Unidades.setText(null);
            Unidades.requestFocus();
            Estilos.removePlaceholderStyle(Unidades);
        }
    }//GEN-LAST:event_UnidadesFocusGained

    private void UnidadesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UnidadesFocusLost
        if(Unidades.getText().length()==0){
            Estilos.addPlaceholderStyle(Unidades);
            Unidades.setText("Unidades Disponibles");
        }
    }//GEN-LAST:event_UnidadesFocusLost

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        String areaSeleccionada = (String) combo.getSelectedItem();
        int num = combo.getSelectedIndex();
        int num1 = 0;
                
        if (combo.getSelectedIndex() != 0) {
            //actualizarTablaInventarioPorArea(areaSeleccionada);
            //cod.setText("" + num + "0---");
            
            try{
                CONSULTASDAO dao = new CONSULTASDAO(Conexion_DB.getConexion());
                int codigo = dao.getCod(num);
                num1 = codigo + 1;
                cod.setText("" + num1);
                
                
            } catch (SQLException ex) {
                //Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("QUE WEY SOY X2");
            }
            
        } else {
            //actualizarTablaInventario();
        }
        
        numfinal = num1;

    }//GEN-LAST:event_comboActionPerformed

    private void NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusGained
        if(Nombre.getText().equals("Nombre")){
            Nombre.setText(null);
            Nombre.requestFocus();
            Estilos.removePlaceholderStyle(Nombre);
        }
    }//GEN-LAST:event_NombreFocusGained

    private void NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusLost
        if(Nombre.getText().length()==0){
            Estilos.addPlaceholderStyle(Nombre);
            Nombre.setText("Nombre");
        }
    }//GEN-LAST:event_NombreFocusLost

    private void PrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecioFocusGained
        if(Precio.getText().equals("Precio")){
            Precio.setText(null);
            Precio.requestFocus();
            Estilos.removePlaceholderStyle(Precio);
        }
    }//GEN-LAST:event_PrecioFocusGained

    private void PrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecioFocusLost
        if(Precio.getText().length()==0){
            Estilos.addPlaceholderStyle(Precio);
            Precio.setText("Precio");
        }
    }//GEN-LAST:event_PrecioFocusLost

    private void CaducidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CaducidadFocusGained
        if(Caducidad.getText().equals("Fecha de Caducidad")){
            Caducidad.setText(null);
            Caducidad.requestFocus();
            Estilos.removePlaceholderStyle(Caducidad);
        }
    }//GEN-LAST:event_CaducidadFocusGained

    private void CaducidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CaducidadFocusLost
        if(Caducidad.getText().length()==0){
            Estilos.addPlaceholderStyle(Caducidad);
            Caducidad.setText("Fecha de Caducidad");
        }
    }//GEN-LAST:event_CaducidadFocusLost

    private void MarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MarcaFocusGained
        if(Marca.getText().equals("Marca")){
            Marca.setText(null);
            Marca.requestFocus();
            Estilos.removePlaceholderStyle(Marca);
        }
    }//GEN-LAST:event_MarcaFocusGained

    private void MarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MarcaFocusLost
        if(Marca.getText().length()==0){
            Estilos.addPlaceholderStyle(Marca);
            Marca.setText("Marca");
        }
    }//GEN-LAST:event_MarcaFocusLost

    private void ContenidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContenidoFocusGained
        if(Contenido.getText().equals("Contenido")){
            Contenido.setText(null);
            Contenido.requestFocus();
            Estilos.removePlaceholderStyle(Contenido);
        }
    }//GEN-LAST:event_ContenidoFocusGained

    private void ContenidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContenidoFocusLost
        if(Contenido.getText().length()==0){
            Estilos.addPlaceholderStyle(Contenido);
            Contenido.setText("Contenido");
        }
    }//GEN-LAST:event_ContenidoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombree = Nombre.getText();
        int areaID = combo.getSelectedIndex();
        double precioo = Double.parseDouble(Precio.getText());
        int unidadess = Integer.parseInt(Unidades.getText());
        String fechaa = Caducidad.getText();
        int codigoB = Integer.parseInt(cod.getText());
        String marcaa = Marca.getText();
        String contenidoo = Contenido.getText();

        try {
            CONSULTASDAO dao = new CONSULTASDAO(Conexion_DB.getConexion());

            boolean exito = dao.crearProd(nombree, areaID, precioo, unidadess, fechaa, codigoB, marcaa, contenidoo);
            
            if (exito) {
                System.out.println("Producto " + nombree + " agregado correctamente");
                Principal2_0 p = new Principal2_0();
                p.actualizarTablaInventario();
            } else {
                System.out.println("Producto no agregado");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();  // Imprimir detalles de error
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Principal2_0 p = new Principal2_0();
        p.actualizarTablaInventario();
    }//GEN-LAST:event_RETURNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Caducidad;
    private javax.swing.JTextField Contenido;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Precio;
    private javax.swing.JButton RETURN;
    private javax.swing.JTextField Unidades;
    private javax.swing.JLabel cod;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    
}
